import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Cárbula</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main + " bg-primary bg-gradient"}>
      <div class="row  justify-content-center align-items-center">
        <div class="col-md-6">
          <img src="../images/logo.svg" class="img-fluid" alt="Logo"></img>
        </div>
        <div class="col-md-6">
          <ul class="list-group list-group-flush">
            <li class="list-group-item bg-transparent"><a href="https://www.carbula.ar/" class="btn btn-outline-light border-0" role="button"><img src="../images/banderas/flgAR.svg" className={styles.icoflg} alt="Bandera AR"></img>Argentina</a></li>
            <li class="list-group-item bg-transparent"><a href="https://www.carbula.cl/" class="btn btn-outline-light border-0" role="button"><img src="../images/banderas/flgCL.svg" className={styles.icoflg} alt="Bandera CL"></img>Chile</a></li>
            <li class="list-group-item bg-transparent"><a href="https://www.carbula.mx/" class="btn btn-outline-light border-0" role="button"><img src="../images/banderas/flgMX.svg" className={styles.icoflg} alt="Bandera MX"></img>Mexico</a></li>
            <li class="list-group-item bg-transparent"><a href="https://www.carbula.uy/" class="btn btn-outline-light border-0" role="button"><img src="../images/banderas/flgUY.svg" className={styles.icoflg} alt="Bandera UY"></img>Uruguay</a></li>
          </ul>
        </div>
      </div>
      </main>

    </div>
  )
}
